##### CONFIGURACIÓN JAVA
export JAVA_HOME=/usr/local/openjdk
export PATH=$PATH:$JAVA_HOME/bin

##### CONFIGURACIÓN HADOOP
export HADOOP_HOME=/opt/hadoop
export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
export PATH=$PATH:$HADOOP_HOME/bin
export PATH=$PATH:$HADOOP_HOME/sbin
